package helpers

import (
	"testing"
	"pgregory.net/rapid"
	"github.com/trinitymorphy69/distributed-systems/types"
	"github.com/trinitymorphy69/distributed-systems/internal/helpers/test-helpers"
)

func TestCheckEvent(t *testing.T) {
	
	rapid.Check(t, func (t *rapid.T)  {


		// This create a slice of random events generated by EventGenerator.
		events := rapid.SliceOfN(rapid.Custom(testhelpers.EventGenerator), 1, -1).Draw(t, "executed")

		err := CheckEvent(events)

		if err == nil {

			for _, event := range events {

				if !isValid(event) {
					t.Fatalf("Batch approved, but found invalid event: %+v", event)
				}
			}

		}

	})

}

func TestCheckEventMinimal(t *testing.T) {
	
	rapid.Check(t, func (t *rapid.T)  {


		// This create a slice of random events generated by EventGenerator.
		events := rapid.SliceOfN(rapid.Custom(testhelpers.MinimalEventGenerator), 1, -1).Draw(t, "executed")

		err := CheckEventMinimal(events)

		if err == nil {

			for _, event := range events {

				if !isValidMinimal(event) {
					t.Fatalf("Batch approved, but found invalid event: %+v", event)
				}
			}

		}

	})

}


func isValid (event types.Event) bool {

	// PROPERTIES OF A VALID EVENT.

	// 1. Process name must not be empty.
	processEmpty := event.Process != ""

	// 2. Process name must satisfy the process naming convention.
	namingConvention := ProcessNamingConvention(event) == nil

	// 3. Event number cannot be less than or equal to zero.
	validSequenceNumber := event.Number > 0

	// 4. Event Lamport clock must not be set.
	validLamportClock := event.LamportClock == 0

	// 5. Event Vector clock must not be set
	validVectorClock := len(event.VectorClock) == 0

	// 6. Event Type must fall between 1 and 3.
	validEventType := event.Type >= 1 && event.Type <= 3

	// 7. Checks that other fields satisfy the selected event type.
	var validTypeProperties bool
	switch event.Type {
	case 1:
		validTypeProperties = event.To != "" && event.From == "" && event.To != event.Process

	case 2:
		validTypeProperties = event.From != "" && event.To == "" && event.From != event.Process

	case 3:
		validTypeProperties = event.To == "" && event.From == ""

	}
	
	return processEmpty && namingConvention && validSequenceNumber && validLamportClock &&
	validVectorClock && validEventType && validTypeProperties


}


func isValidMinimal (event types.EventMinimal) bool {

	// PROPERTIES OF A VALID EVENT.

	// 1. Process name must not be empty.
	processEmpty := event.Process != ""

	// 2. Process name must satisfy the process naming convention.
	namingConvention := ProcessNamingConventionforMinimalEvent(event) == nil

	// 3. Event number cannot be less than or equal to zero.
	validSequenceNumber := event.Number > 0
	
	return processEmpty && namingConvention && validSequenceNumber

}




