package helpers

import (
	"testing"
	"pgregory.net/rapid"
	"github.com/trinitymorphy69/distributed-systems/internal/helpers/test-helpers"
)

func TestEventOrdering(t *testing.T) {

	rapid.Check(t, func(t *rapid.T) {

		// This create a slice of random events generated by EventGenerator.
		input := rapid.SliceOfN(rapid.Custom(testhelpers.EventGenerator), 1, -1).Draw(t, "input")

		output, err := EventOrdering(input)

		if err == nil {

			if len(input) != len(output) {

			t.Fatalf("Length mismatch; Output: %v, Input: %v", len(output), len(input))

			}

			for i := 0; i < len(output) - 1; i++ {

				a := output[i]
				b := output[i+1]

				if a.Process == b.Process {

					if b.Number <= a.Number {
						t.Fatalf("Main function passed. But on Process %v, %v should come before %v", a.Process, a.Number, b.Number)
					}
				}
			}

		}

		
	})
	
}