package helpers

import (
	"testing"
	"pgregory.net/rapid"
	"github.com/trinitymorphy69/distributed-systems/internal/helpers/test-helpers"
)

func TestMatchSendReceive(t *testing.T) {

	rapid.Check(t, func(t *rapid.T) {

		// This create a slice of random events generated by EventGenerator.
		input := rapid.SliceOfN(rapid.Custom(testhelpers.EventGenerator), 1, -1).Draw(t, "input")

		output, err := MatchSendReceive(input)

		if err == nil {

			// This loop compares two consecutive events in the output of the MatchSendReceive
			// function with the checkTrue function to confirm that they are matching events.

			for i := 0; i < len(output)-1; i++ {

				a := output[i]
				b := output[i+1]

				valid := testhelpers.CheckTrue(a, b)

				if !valid {
					t.Fatalf("MatchSendReceive passed. However event %v on process %v is not the receive for event %v on process %v ", b.Number, b.Process, a.Number, a.Process)
				}
			}

		}

	})
	
}