package helpers

import (
	
	"reflect"
	"testing"
	"pgregory.net/rapid"
	"github.com/trinitymorphy69/distributed-execution-fundamentals/types"
	"github.com/trinitymorphy69/distributed-execution-fundamentals/internal/helpers/test-helpers"
	
)

func TestCheckTransitivity(t *testing.T) {

	rapid.Check(t, func(t *rapid.T) {

		// This create a slice of slices of random events generated by MinimalEventGenerator.
		input := rapid.SliceOfN(rapid.SliceOfN(rapid.Custom(testhelpers.EventGenerator), 2, 2), 2, -1).Draw(t, "executed")

		output, err := CheckTransitivity(input)

		if err == nil {

			if !transitivityCheck(input, output) {

				t.Fatalf("CheckTransitivity function passed. However the corresponding inputs to the outputs cannot be derived. %v, %v", input, output)

			}

		}

	})
	
}


func transitivityCheck(input, output [][]types.Event) bool {

	// If we have a slice [x,y] within the output slice, it means that we have 
	// [x, a] && [a, y] in the input slice. This is the property we will check for. 

	startsWithFirst := [][]types.Event{}
	endsWithLast := [][]types.Event{}

	if len(input) < 2 {
		return false
	}


	// We iterate through all pairs of the resulting output of the Check Transitivity function
	for _, outputPair := range output {

		// Based on the format that an element [x, y] is the transitive of [x, a] && [a, y],
		// We store both x and y in different variables. The goal is to compare it with elements
		// from the iteration of input. 
		x := outputPair[0]
		y := outputPair[1]

		// We look for the slices where the last element is y or the first element is x and 
		// append them to their respective slices.
		for _, inputPair := range input {

			if reflect.DeepEqual(inputPair[0], x) {
				startsWithFirst = append(startsWithFirst, inputPair)
			}

			if reflect.DeepEqual(inputPair[1], y) {
				endsWithLast = append(endsWithLast, inputPair)
			}

		}

		// We go through both startsWithFirst and endsWithLast slice to get elements within 
		// that have the same element in the second and first position relatively. 
		for _, event := range startsWithFirst {

			a := event[1]

			for _, anotherEvent := range endsWithLast {

				if reflect.DeepEqual(anotherEvent[0], a) {
					return true
				}
			}
		}

	}

	return false

}